# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7366f647ad7e60cc5e200b424bfe287114482c9734efd57cc6b7e3b7fbc4a578be7ea57503997b64c9653a04f7469e9dc25695a4e23ad45740865bebe91c30db

test:
  secret_key_base: 511c1d38bb777f3ec2ae41cb6bccebd28e40e53e301c8cd538333a9acb9e7048e5124d25d6a853fe2cff7170caf50ec9de2bfcdf1b0d91721d307e26f7a7f11f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
